### ISSUE TITLE
Ability to customize internal http client

### ISSUE THREAD

**Issue by welandaz** [Kount/kount-ris-java-sdk#29]
Hey everyone!

We have a use case, where we require all our requests to be routed via internal proxy. The configuration for that is currently specified via -Dhttps.proxyHost=... and -Dhttps.proxyPort.
In the old version of the SDK, plain Java mechanisms were used for establishing communication and our proxy settings were picked up. 
However, the new version uses Apache HttpClient, where we would actually need to enable this feature (e.g. via useSystemProperties() method) during the client's setup (otherwise Java system properties aren't used)

Hence, I wanted to discuss with you the possibility to add a feature, which allows either enabling this specific option or perhaps just setting up our own custom http client (in case there won't be any - default one will be used).

I can, of course, provide the PR with this if this makes sense for you.
Thank you!

**Comment by dharp-kount** [comment]
Thanks for the report.  I would lean towards leveraging the system properties if provided rather than accepting a custom http client for 2 primary reasons.  First, better backwards compatibility if others are using these same proxy options prior to upgrading to the newer SDK.  Second, if the SDK accepted a custom HttpClient and the need ever arose to swap out Apache's library for an alternative, we would be forced to introduce a breaking change, while it could be non-breaking by ensuring we passed along the system properties to any implementation.
I'll submit this to our backlog for prioritization.  If you'd like to submit a PR that could reduce the turn around time for the feature.

**Comment by welandaz** [comment]
Hey @dharp-kount!

Thanks a lot for responding!

Yeah, that makes sense. So the solution would be to just enable use of system properties for the http client as a default option, right? (if there are any, it will pick them up for proxy purposes)

If that's the case, I can provide a PR.

**Comment by dharp-kount** [comment]
> 

Yes, that's the solution I think would fit best!

**Comment by welandaz** [comment]
Hey @dharp-kount !

I've prepared a small PR to address the issue - https://github.com/Kount/kount-ris-java-sdk/pull/30.

I'm not able to assign reviewers though, so posting it here. 
Will address any issues you might have with it.
